name = "agd"
version = "0.1.0"
defaultTargets = ["AGD"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "AGD"
srcDir = "."
globs = ["AGD.*"]

[[lean_exe]]
name = "agd_exe"
root = "Main"
