/-
  Minimal Admissible Quotient (Q*)
  Operational scaffold for Lean 4
  Goal: unique minimal / initial state space that preserves Ω and C
-/

namespace AGD

universe u

/-- Operational state. Replace the fields with your real payload later. -/
structure State (α : Type u) where
  id        : Nat
  payload   : α
  deriving DecidableEq, Repr

/-- Invariant signature. Must be decidable for runtime checks. -/
abbrev Omega (α : Type u) := State α → Nat

/-- Covariant / constitutional law. Must be decidable. -/
abbrev Covariant (α : Type u) := State α → Nat

/-- An operator is just a state transformer. -/
abbrev Operator (α : Type u) := State α → State α

/-- Admissible operator: preserves both Ω and C. -/
def Admissible (α : Type u) (Ω : Omega α) (C : Covariant α) (T : Operator α) : Prop :=
  ∀ s, Ω (T s) = Ω s ∧ C (T s) = C s

/-- The AGD equivalence relation generated by the pair (Ω, C). -/
def AGDEquiv (α : Type u) (Ω : Omega α) (C : Covariant α) (s₁ s₂ : State α) : Prop :=
  Ω s₁ = Ω s₂ ∧ C s₁ = C s₂

theorem AGDEquiv.refl (α : Type u) (Ω : Omega α) (C : Covariant α) (s : State α) :
    AGDEquiv α Ω C s s := ⟨rfl, rfl⟩

theorem AGDEquiv.symm (α : Type u) (Ω : Omega α) (C : Covariant α)
    {s₁ s₂ : State α} (h : AGDEquiv α Ω C s₁ s₂) :
    AGDEquiv α Ω C s₂ s₁ := ⟨h.1.symm, h.2.symm⟩

theorem AGDEquiv.trans (α : Type u) (Ω : Omega α) (C : Covariant α)
    {s₁ s₂ s₃ : State α}
    (h₁₂ : AGDEquiv α Ω C s₁ s₂) (h₂₃ : AGDEquiv α Ω C s₂ s₃) :
    AGDEquiv α Ω C s₁ s₃ :=
  ⟨h₁₂.1.trans h₂₃.1, h₁₂.2.trans h₂₃.2⟩

def agdSetoid (α : Type u) (Ω : Omega α) (C : Covariant α) : Setoid (State α) where
  r     := AGDEquiv α Ω C
  iseqv := ⟨AGDEquiv.refl α Ω C, AGDEquiv.symm α Ω C, AGDEquiv.trans α Ω C⟩

def QStar (α : Type u) (Ω : Omega α) (C : Covariant α) : Type u :=
  Quotient (agdSetoid α Ω C)

def pi (α : Type u) (Ω : Omega α) (C : Covariant α) : State α → QStar α Ω C :=
  Quotient.mk (agdSetoid α Ω C)

def OmegaBar (α : Type u) (Ω : Omega α) (C : Covariant α) : QStar α Ω C → Nat :=
  Quotient.lift Ω (fun _ _ h => h.1)

def CBar (α : Type u) (Ω : Omega α) (C : Covariant α) : QStar α Ω C → Nat :=
  Quotient.lift C (fun _ _ h => h.2)

noncomputable def TBar
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (T : Operator α) (hT : Admissible α Ω C T) :
    QStar α Ω C → QStar α Ω C :=
  Quotient.lift (fun s => pi α Ω C (T s))
    (by
      intro s₁ s₂ h
      apply Quotient.sound
      have hΩ := h.1
      have hC := h.2
      have hT₁ := hT s₁
      have hT₂ := hT s₂
      have hTΩ₁ := hT₁.1
      have hTC₁ := hT₁.2
      have hTΩ₂ := hT₂.1
      have hTC₂ := hT₂.2
      constructor
      · rw [hTΩ₁, hTΩ₂, hΩ]
      · rw [hTC₁, hTC₂, hC])

theorem TBar_sound
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (T : Operator α) (hT : Admissible α Ω C T) (s : State α) :
    TBar α Ω C T hT (pi α Ω C s) = pi α Ω C (T s) := by
  rfl

theorem descends
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (T : Operator α) (hT : Admissible α Ω C T) :
    ∃ Tbar : QStar α Ω C → QStar α Ω C,
      ∀ s, Tbar (pi α Ω C s) = pi α Ω C (T s) :=
  ⟨TBar α Ω C T hT, fun _ => rfl⟩

structure PreservingQuotient (α : Type u) (Ω : Omega α) (C : Covariant α) where
  carrier : Type u
  proj    : State α → carrier
  respects_equiv : ∀ s₁ s₂, AGDEquiv α Ω C s₁ s₂ → proj s₁ = proj s₂
  omega_desc : ∃ Ω' : carrier → Nat, ∀ s, Ω' (proj s) = Ω s
  c_desc     : ∃ C'  : carrier → Nat, ∀ s, C'  (proj s) = C s

noncomputable def uniqueMorph
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (Q : PreservingQuotient α Ω C) :
    QStar α Ω C → Q.carrier :=
  Quotient.lift Q.proj Q.respects_equiv

theorem uniqueMorph_unique
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (Q : PreservingQuotient α Ω C)
    (f : QStar α Ω C → Q.carrier)
    (h : ∀ s, f (pi α Ω C s) = Q.proj s) :
    f = uniqueMorph α Ω C Q := by
  apply funext
  intro x
  unfold QStar at x
  induction x using Quotient.ind
  rename_i s
  change f (pi α Ω C s) = uniqueMorph α Ω C Q (pi α Ω C s)
  rw [h s]
  rfl

class Fintype (α : Type u)

theorem minimality_sketch
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    [Fintype (State α)]
    (Q : PreservingQuotient α Ω C)
    [Fintype Q.carrier] :
    True := by
  trivial

def interchangeable
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (s₁ s₂ : State α) : Prop :=
  pi α Ω C s₁ = pi α Ω C s₂

theorem interchangeable_iff
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (s₁ s₂ : State α) :
    interchangeable α Ω C s₁ s₂ ↔ AGDEquiv α Ω C s₁ s₂ := by
  unfold interchangeable
  constructor
  · intro h
    exact Quotient.exact h
  · intro h
    exact Quotient.sound h

theorem admission_iff_descends
    (α : Type u) (Ω : Omega α) (C : Covariant α)
    (T : Operator α) :
    Admissible α Ω C T ↔
      ∃ Tbar : QStar α Ω C → QStar α Ω C, (∀ s, Tbar (pi α Ω C s) = pi α Ω C (T s)) ∧ ∀ x, Tbar x = x := by
  constructor
  · intro hT
    refine ⟨TBar α Ω C T hT, ?_⟩
    constructor
    · intro s
      rfl
    · intro x
      unfold QStar at x
      induction x using Quotient.ind
      rename_i s
      change TBar α Ω C T hT (pi α Ω C s) = pi α Ω C s
      rw [TBar_sound]
      apply Quotient.sound
      exact hT s
  · intro h
    cases h with
    | intro Tbar h_and =>
      have h_eq := h_and.1
      have h_id := h_and.2
      intro s
      have h1 : Tbar (pi α Ω C s) = pi α Ω C (T s) := h_eq s
      have h2 : Tbar (pi α Ω C s) = pi α Ω C s := h_id (pi α Ω C s)
      have h3 : pi α Ω C (T s) = pi α Ω C s := by rw [← h1, h2]
      exact Quotient.exact h3

-- ==========================================
-- CONSTITUTIONAL METAMODEL DEFINITIONS
-- ==========================================

structure Invariants (α : Type u) where
  omega : Omega α
  covariant : Covariant α

structure ConstitutionalObject (α : Type u) where
  state : State α
  invariants : Invariants α

structure Witness (α : Type u) (inv : Invariants α) (op : Operator α) where
  admissible : Admissible α inv.omega inv.covariant op

structure Fiber (α : Type u) (inv : Invariants α) (val : Nat × Nat) where
  states : List (State α)
  all_eq : ∀ s ∈ states, inv.omega s = val.1 ∧ inv.covariant s = val.2

structure Registry (α : Type u) (inv : Invariants α) where
  operators : List (Operator α)
  witnesses : ∀ op ∈ operators, Admissible α inv.omega inv.covariant op

def replay (α : Type u) : List (Operator α) → State α → State α
  | [], s => s
  | op :: ops, s => replay α ops (op s)

theorem replay_preserves_invariants
    (α : Type u) (inv : Invariants α) (ops : List (Operator α))
    (hops : ∀ op ∈ ops, Admissible α inv.omega inv.covariant op)
    (s : State α) :
    inv.omega (replay α ops s) = inv.omega s ∧ inv.covariant (replay α ops s) = inv.covariant s := by
  induction ops generalizing s with
  | nil =>
    exact ⟨rfl, rfl⟩
  | cons op ops ih =>
    have h_op : Admissible α inv.omega inv.covariant op := hops op (List.Mem.head _)
    have h_ops : ∀ op ∈ ops, Admissible α inv.omega inv.covariant op := fun op' h => hops op' (List.Mem.tail _ h)
    have ih_res := ih h_ops (op s)
    have h_admissible := h_op s
    change inv.omega (replay α ops (op s)) = inv.omega s ∧ inv.covariant (replay α ops (op s)) = inv.covariant s
    rw [ih_res.1, ih_res.2]
    exact h_admissible

structure Replay (α : Type u) where
  run : List (Operator α) → State α → State α

structure Compiler (α : Type u) (β : Type) where
  compile : State α → β

structure Serialization (α : Type u) where
  serialize : State α → String

structure Hash (α : Type u) where
  hash : State α → Nat

structure Builder (α : Type u) where
  build : Nat → α → State α

end AGD
