name: S6 COCO Benchmark

on:
  push:
    branches: [ "main" ]

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install numpy cocoex

    - name: Run S6 COCO Benchmark
      run: |
        python coco_s6_benchmark.py

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: s6-coco-results
        path: S6_RESULTS/
