name: Lean Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Set Toolchain
        run: |
          elan default stable
          lean --version

      - name: Init Lake
        run: |
          rm -rf .lake
          lake update

      - name: Fetch Mathlib Cache
        run: lake exe cache get

      - name: Build
        run: lake build
